name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'

env:
  NODE: lts/*
  REPOSITORY: self
  BUILD_BRANCH: build
  BUILD_FOLDER: docs

jobs:
  init:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: ${{ env.NODE }}

      - name: Init workspace
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: ${{ env.REPOSITORY }}
          BRANCH: ${{ env.BUILD_BRANCH }}
          FOLDER: ${{ env.BUILD_FOLDER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
