name: Build, lint, deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'

env:
  NODE: lts/*
  REPOSITORY: self
  BUILD_BRANCH: build
  BUILD_FOLDER: docs

jobs:
  init:
    runs-on: unbuntu-latest

    steps:
      - uses: actions/checkout/v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: $NODE

      - name: Init workspace
        run: npm ci

  lint:
    needs: init

    runs-on: ubuntu-latest

    steps:
      - name: Run ESLint
        run: npm run lint

  build:
    needs: lint

    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: npm run build

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Deploy
        uses: s0/github-publish-subdir-action@develop
        env:
          REPO: $REPOSITORY
          BRANCH: $BUILD_BRANCH
          FOLDER: $BUILD_FOLDER
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
